pluginManagement {
    repositories {
        maven { name = "Fabric"; url = uri("https://maven.fabricmc.net/") }
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { name = "Fabric"; url = uri("https://maven.fabricmc.net/") }
    }
}
rootProject.name = "XperimentAntiCheat"
